export const Strings = {
  app: {
    name: 'Foot Is Life',
    tagline: 'Améliore ta frappe, séance après séance',
  },

  auth: {
    login: 'Se connecter',
    signup: "S'inscrire",
    logout: 'Se déconnecter',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    displayName: 'Prénom ou pseudo',
    noAccount: "Pas encore de compte ?",
    hasAccount: 'Déjà un compte ?',
    createAccount: 'Créer un compte',
    welcomeBack: 'Content de te revoir !',
    welcomeNew: 'Rejoins Foot Is Life',
    errorInvalidEmail: 'Adresse e-mail invalide.',
    errorWeakPassword: 'Le mot de passe doit contenir au moins 6 caractères.',
    errorEmailInUse: 'Cette adresse e-mail est déjà utilisée.',
    errorWrongPassword: 'Mot de passe incorrect.',
    errorUserNotFound: 'Aucun compte trouvé avec cette adresse.',
    errorGeneric: 'Une erreur est survenue. Réessaie.',
    forgotPassword: 'Mot de passe oublié ?',
    forgotPasswordTitle: 'Réinitialiser le mot de passe',
    forgotPasswordDesc: 'Entre ton adresse e-mail. Tu recevras un lien pour créer un nouveau mot de passe.',
    forgotPasswordSend: 'Envoyer le lien',
    forgotPasswordSuccess: 'Un e-mail de réinitialisation a été envoyé. Vérifie ta boîte de réception (et tes spams).',
    forgotPasswordBackToLogin: 'Retour à la connexion',
  },

  tabs: {
    home: 'Accueil',
    history: 'Historique',
    profile: 'Profil',
  },

  home: {
    greeting: 'Salut',
    startSession: 'Commencer une séance',
    lastScore: 'Dernier score',
    totalSessions: 'Séances',
    averageScore: 'Score moyen',
    bestScore: 'Meilleur score',
    noSessionsYet: "Tu n'as pas encore fait de séance.",
    firstSessionCta: 'Filme ta première frappe !',
  },

  session: {
    chooseMode: 'Comment veux-tu procéder ?',
    filmNow: 'Filmer maintenant',
    importVideo: 'Importer une vidéo',
    filmNowDesc: 'Utilise la caméra pour filmer ta frappe en direct.',
    importDesc: 'Importe une vidéo depuis ta photothèque.',

    instructionsFrontTitle: 'Vue de face',
    instructionsFrontDesc: 'Place le téléphone devant le joueur, à environ 3-4 mètres.',
    instructionsFrontTip1: 'Le joueur doit être visible en entier.',
    instructionsFrontTip2: 'Tiens le téléphone stable, à hauteur de hanches.',
    instructionsFrontTip3: 'Filme la frappe complète : approche, frappe et suivi.',
    instructionsFrontStart: "Commencer l'enregistrement",

    instructionsBackTitle: 'Vue de dos',
    instructionsBackDesc: 'Place le téléphone derrière le joueur, à environ 3-4 mètres.',
    instructionsBackTip1: "On doit voir la trajectoire d'approche.",
    instructionsBackTip2: 'Le pied d\'appui et la jambe de frappe doivent être visibles.',
    instructionsBackTip3: "Filme l'ensemble du geste jusqu'à la fin.",
    instructionsBackStart: "Commencer l'enregistrement",
    skipBackView: 'Passer cette étape',
    skipBackViewConfirm: "L'analyse sera moins précise avec une seule vidéo. Continuer ?",

    recording: 'Enregistrement en cours...',
    stopRecording: "Arrêter l'enregistrement",
    retake: 'Recommencer',
    useVideo: 'Utiliser cette vidéo',

    validationTitle: 'Vérifie tes vidéos',
    frontVideo: 'Vidéo de face',
    backVideo: 'Vidéo de dos',
    noBackVideo: 'Pas de vidéo de dos',
    launchAnalysis: "Lancer l'analyse",
    redo: 'Recommencer',

    analyzingTitle: 'Analyse en cours...',
    analyzingUpload: 'Envoi des vidéos...',
    analyzingUploadProgress: 'Envoi en cours…',
    analyzingUploadFront: 'Envoi de la vidéo de face…',
    analyzingUploadBack: 'Envoi de la vidéo de dos…',
    analyzingUploadDone: 'Vidéos envoyées',
    analyzingUploadPartialOk:
      "Envoi partiel réussi. L'analyse se poursuit avec les vidéos disponibles.",
    analyzingUploadFailed:
      "L'envoi a échoué, mais la séance est conservée localement. Tu pourras réessayer plus tard.",
    analyzingProcess: 'Analyse de ta frappe...',
    analyzingTips: 'Préparation des conseils...',
    analyzingDone: 'Terminé !',
    analyzingErrorSave: 'Impossible de sauvegarder la séance. Vérifie ta connexion et réessaie.',
    analyzingErrorAnalysis: "Une erreur est survenue pendant l'analyse. Réessaie ou reviens à l'accueil.",
  },

  results: {
    title: 'Résultats',
    globalScore: 'Score global',
    confidence: 'Niveau de confiance',
    confidenceHigh: 'Élevé (2 angles)',
    confidenceMedium: 'Modéré (1 angle)',
    partialAnalysis: 'Analyse partielle',
    partialAnalysisDesc: "Seule une vidéo a été analysée. Filme les deux angles pour une analyse plus complète.",
    frontScores: 'Vue de face',
    backScores: 'Vue de dos',
    commonScores: 'Analyse générale',
    strengths: 'Tes points forts',
    defects: 'À corriger',
    exercises: 'Exercices recommandés',
    tips: 'Conseils',
    severityLight: 'Léger',
    severityMedium: 'Moyen',
    severityImportant: 'Important',
    backToHome: "Retour à l'accueil",
    newSession: 'Nouvelle séance',
    share: 'Partager',
    shareTitle: 'Mon analyse Foot Is Life',
    shareIntro: "Voici mon analyse de frappe sur Foot Is Life :",
    shareScore: 'Score global',
    shareStrengths: 'Points forts',
    shareDefects: 'À améliorer',
    shareMotivation: 'La progression passe par la répétition !',
    shareFooter: 'Analysé avec Foot Is Life',
    disclaimer: '⚠️ Cette analyse est une estimation simplifiée basée sur les métadonnées de ta vidéo. Elle ne remplace pas l\'avis d\'un coach professionnel.',
  },

  history: {
    title: 'Historique',
    noSessions: 'Aucune séance pour le moment.',
    noSessionsCta: 'Commence ta première séance !',
    sessionDate: 'Séance du',
    angles: 'angles',
    angle: 'angle',
    deleteConfirmTitle: 'Supprimer cette séance ?',
    deleteConfirmMessage: 'Cette action est irréversible. La séance et ses vidéos seront définitivement supprimées.',
    deleteSuccess: 'Séance supprimée.',
    deleteError: 'Impossible de supprimer la séance. Réessaie.',
    deleting: 'Suppression...',
  },

  profile: {
    title: 'Mon profil',
    memberSince: 'Membre depuis',
    stats: 'Statistiques',
    progression: 'Progression',
    frequentDefects: 'Défauts les plus fréquents',
    priorityAxes: 'Axes prioritaires',
    noData: 'Pas assez de données pour afficher la progression.',
  },

  scores: {
    upperBodyAlignment: 'Alignement du haut du corps',
    stability: 'Stabilité',
    torsoOpenness: 'Ouverture du buste',
    gestureSymmetry: 'Symétrie du geste',
    posturalQuality: 'Qualité posturale',
    approachTrajectory: "Trajectoire d'approche",
    supportFootPlacement: "Placement du pied d'appui",
    strikingLegTrajectory: 'Trajectoire jambe de frappe',
    globalGestureAxis: 'Axe global du geste',
    postImpactBalance: 'Équilibre après impact',
    approachAngle: "Angle d'approche",
    supportFootPosition: "Position du pied d'appui",
    torsoOrientation: 'Orientation du buste',
    strikingLegMovement: 'Mouvement jambe de frappe',
    estimatedContactPoint: 'Point de contact estimé',
    postStrikeBalance: 'Équilibre après frappe',
    overallTiming: 'Timing global',
  },

  common: {
    cancel: 'Annuler',
    confirm: 'Confirmer',
    continue: 'Continuer',
    loading: 'Chargement...',
    error: 'Erreur',
    retry: 'Réessayer',
    ok: 'OK',
    yes: 'Oui',
    no: 'Non',
    save: 'Enregistrer',
    delete: 'Supprimer',
    outOf100: '/ 100',
  },

  permissions: {
    cameraRequired: "L'accès à la caméra est nécessaire pour filmer ta frappe.",
    galleryRequired: "L'accès à la photothèque est nécessaire pour importer une vidéo.",
    openSettings: 'Ouvrir les réglages',
  },
};
